excluded:
  - StoreSearchAppTests
  - StoreSearchAppUITests
  - StoreSearchApp.xcodeproj

opt_in_rules:
  - closure_spacing

disabled_rules:
  - line_length # User Xcode page column guide
  - multiple_closures_with_trailing_closure
  #temp setting
  - shorthand_operator
  - type_body_length
  - force_cast
  - file_length
  - function_body_length
#  - type_name
  - large_tuple
  - function_parameter_count

indentation: 4

identifier_name:
  min_length: 1
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false #temp
type_name:
  min_length: 1
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false #temp
line_length:
  error: 500
cyclomatic_complexity: #temp
  error: 150

reporter: "html"
